export const EXCEL_ASSESSMENTS = [
  // === ANGGY -> Deny Ferdiansyah === Excel Total: 70.8, Calculated: 70.8
  { penilai: 'anggy', kandidat: 'Deny Ferdiansyah', scores: [
    { kode: 'A100', nilai: 6, check_ada: true },
    { kode: 'A200', nilai: 0, check_ada: false },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 2, check_ada: true },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 12, check_ada: false },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 2, check_ada: false },
    { kode: 'C140', nilai: 3, check_ada: false },
    { kode: 'D110', nilai: 1, check_ada: false },
    { kode: 'D120', nilai: 6, check_ada: false },
    { kode: 'D130', nilai: 5, check_ada: false },
    { kode: 'D140', nilai: 6, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 3, check_ada: false },
    { kode: 'E300', nilai: 2, check_ada: false },
    { kode: 'F100', nilai: 3.2, check_ada: false },
    { kode: 'F200', nilai: 0.6, check_ada: false },
    { kode: 'G100', nilai: 4, check_ada: false }
  ]},
  // === WAHYU -> Ilham Ambia Putra === Excel Total: 66.2, Calculated: 66.2
  { penilai: 'wahyu', kandidat: 'Ilham Ambia Putra', scores: [
    { kode: 'A100', nilai: 0, check_ada: false },
    { kode: 'A200', nilai: 4, check_ada: true },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 6, check_ada: false },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 2, check_ada: false },
    { kode: 'C140', nilai: 6, check_ada: false },
    { kode: 'D110', nilai: 1.5, check_ada: false },
    { kode: 'D120', nilai: 8, check_ada: false },
    { kode: 'D130', nilai: 4, check_ada: false },
    { kode: 'D140', nilai: 7.5, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 4, check_ada: false },
    { kode: 'E300', nilai: 2, check_ada: false },
    { kode: 'F100', nilai: 1.6, check_ada: false, keterangan: 'UMR DEPOK (TERBUKA' },
    { kode: 'F200', nilai: 0.6, check_ada: false },
    { kode: 'G100', nilai: 4, check_ada: false }
  ]},
  // === WAHYU -> Mohamad Dicky === Excel Total: 62.2, Calculated: 62.2
  { penilai: 'wahyu', kandidat: 'Mohamad Dicky', scores: [
    { kode: 'A100', nilai: 0, check_ada: false },
    { kode: 'A200', nilai: 0, check_ada: false },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 3, check_ada: false },
    { kode: 'C120', nilai: 8, check_ada: false },
    { kode: 'C130', nilai: 1.5, check_ada: false },
    { kode: 'C140', nilai: 4.5, check_ada: false },
    { kode: 'D110', nilai: 2, check_ada: false },
    { kode: 'D120', nilai: 10, check_ada: false },
    { kode: 'D130', nilai: 3, check_ada: false },
    { kode: 'D140', nilai: 7.5, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 4, check_ada: false },
    { kode: 'E300', nilai: 2.5, check_ada: false },
    { kode: 'F100', nilai: 2.4, check_ada: false, keterangan: 'UMR DEPOK (TERBUKA)' },
    { kode: 'F200', nilai: 0.8, check_ada: false },
    { kode: 'G100', nilai: 4, check_ada: false }
  ]},
  // === WAHYU -> M. Doni Waseso === Excel Total: 58, Calculated: 58
  { penilai: 'wahyu', kandidat: 'M. Doni Waseso', scores: [
    { kode: 'A100', nilai: 6, check_ada: true },
    { kode: 'A200', nilai: 0, check_ada: false },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 0, check_ada: false },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 6, check_ada: false },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 1, check_ada: false },
    { kode: 'C140', nilai: 4.5, check_ada: false },
    { kode: 'D110', nilai: 1, check_ada: false },
    { kode: 'D120', nilai: 4, check_ada: false },
    { kode: 'D130', nilai: 4, check_ada: false },
    { kode: 'D140', nilai: 6, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 3, check_ada: false },
    { kode: 'E300', nilai: 1.5, check_ada: false },
    { kode: 'F100', nilai: 3.2, check_ada: false, keterangan: '>3JT / MENGIKUTI' },
    { kode: 'F200', nilai: 0.8, check_ada: false },
    { kode: 'G100', nilai: 3, check_ada: false }
  ]},
  // === URIP -> Ilham Ambia Putra === Excel Total: 61.2, Calculated: 61.2
  { penilai: 'urip', kandidat: 'Ilham Ambia Putra', scores: [
    { kode: 'A100', nilai: 0, check_ada: false },
    { kode: 'A200', nilai: 4, check_ada: true },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 3, check_ada: false },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 2, check_ada: false },
    { kode: 'C140', nilai: 6, check_ada: false },
    { kode: 'D110', nilai: 1.5, check_ada: false },
    { kode: 'D120', nilai: 10, check_ada: false },
    { kode: 'D130', nilai: 4, check_ada: false },
    { kode: 'D140', nilai: 4.5, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 4, check_ada: false },
    { kode: 'E300', nilai: 2, check_ada: false },
    { kode: 'F100', nilai: 0.8, check_ada: false },
    { kode: 'F200', nilai: 0.4, check_ada: false },
    { kode: 'G100', nilai: 4, check_ada: false }
  ]},
  // === URIP -> Mohamad Dicky === Excel Total: 55.9, Calculated: 55.9
  { penilai: 'urip', kandidat: 'Mohamad Dicky', scores: [
    { kode: 'A100', nilai: 0, check_ada: false },
    { kode: 'A200', nilai: 4, check_ada: true },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 6, check_ada: false },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 1, check_ada: false },
    { kode: 'C140', nilai: 1.5, check_ada: false },
    { kode: 'D110', nilai: 2, check_ada: false },
    { kode: 'D120', nilai: 8, check_ada: false },
    { kode: 'D130', nilai: 3, check_ada: false },
    { kode: 'D140', nilai: 6, check_ada: false },
    { kode: 'E100', nilai: 4.5, check_ada: false },
    { kode: 'E200', nilai: 3, check_ada: false },
    { kode: 'E300', nilai: 1.5, check_ada: false },
    { kode: 'F100', nilai: 1.6, check_ada: false },
    { kode: 'F200', nilai: 0.8, check_ada: false },
    { kode: 'G100', nilai: 4, check_ada: false }
  ]},
  // === URIP -> M. Doni Waseso === Excel Total: 61.3, Calculated: 61.3
  { penilai: 'urip', kandidat: 'M. Doni Waseso', scores: [
    { kode: 'A100', nilai: 6, check_ada: true },
    { kode: 'A200', nilai: 0, check_ada: false },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 0, check_ada: false },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 6, check_ada: false },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 1, check_ada: false },
    { kode: 'C140', nilai: 4.5, check_ada: false },
    { kode: 'D110', nilai: 1, check_ada: false },
    { kode: 'D120', nilai: 6, check_ada: false },
    { kode: 'D130', nilai: 3, check_ada: false },
    { kode: 'D140', nilai: 7.5, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 3, check_ada: false },
    { kode: 'E300', nilai: 1.5, check_ada: false },
    { kode: 'F100', nilai: 4, check_ada: false },
    { kode: 'F200', nilai: 0.8, check_ada: false },
    { kode: 'G100', nilai: 3, check_ada: false }
  ]},
  // === ANGGY -> Ilham Ambia Putra === Excel Total: 60, Calculated: 60
  { penilai: 'anggy', kandidat: 'Ilham Ambia Putra', scores: [
    { kode: 'A100', nilai: 0, check_ada: false },
    { kode: 'A200', nilai: 4, check_ada: true },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 3, check_ada: false },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 1.5, check_ada: false },
    { kode: 'C140', nilai: 6, check_ada: false },
    { kode: 'D110', nilai: 2, check_ada: false },
    { kode: 'D120', nilai: 6, check_ada: false },
    { kode: 'D130', nilai: 4, check_ada: false },
    { kode: 'D140', nilai: 6, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 3, check_ada: false },
    { kode: 'E300', nilai: 2.5, check_ada: false },
    { kode: 'F100', nilai: 2.4, check_ada: false, keterangan: 'UMR DEPOK - 4,9 (NEGO)' },
    { kode: 'F200', nilai: 0.6, check_ada: false },
    { kode: 'G100', nilai: 4, check_ada: false }
  ]},
  // === ANGGY -> Mohamad Dicky === Excel Total: 59.5, Calculated: 59.5
  { penilai: 'anggy', kandidat: 'Mohamad Dicky', scores: [
    { kode: 'A100', nilai: 0, check_ada: false },
    { kode: 'A200', nilai: 4, check_ada: true },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 3, check_ada: false },
    { kode: 'C120', nilai: 8, check_ada: false },
    { kode: 'C130', nilai: 1.5, check_ada: false },
    { kode: 'C140', nilai: 1.5, check_ada: false },
    { kode: 'D110', nilai: 2, check_ada: false },
    { kode: 'D120', nilai: 8, check_ada: false },
    { kode: 'D130', nilai: 2, check_ada: false },
    { kode: 'D140', nilai: 6, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 4, check_ada: false },
    { kode: 'E300', nilai: 2.5, check_ada: false },
    { kode: 'F100', nilai: 3.2, check_ada: false, keterangan: 'MIN. UMR (NEGO)' },
    { kode: 'F200', nilai: 0.8, check_ada: false },
    { kode: 'G100', nilai: 4, check_ada: false }
  ]},
  // === ANGGY -> M. Doni Waseso === Excel Total: 63, Calculated: 63
  { penilai: 'anggy', kandidat: 'M. Doni Waseso', scores: [
    { kode: 'A100', nilai: 6, check_ada: true },
    { kode: 'A200', nilai: 0, check_ada: false },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 0, check_ada: false },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 6, check_ada: false },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 1, check_ada: false },
    { kode: 'C140', nilai: 4.5, check_ada: false },
    { kode: 'D110', nilai: 1.5, check_ada: false },
    { kode: 'D120', nilai: 6, check_ada: false },
    { kode: 'D130', nilai: 4, check_ada: false },
    { kode: 'D140', nilai: 7.5, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 3, check_ada: false },
    { kode: 'E300', nilai: 1.5, check_ada: false },
    { kode: 'F100', nilai: 3.2, check_ada: false },
    { kode: 'F200', nilai: 0.8, check_ada: false },
    { kode: 'G100', nilai: 4, check_ada: false }
  ]},
  // === MUCHLIS -> Ilham Ambia Putra === Excel Total: 58.8, Calculated: 58.8
  { penilai: 'muchlis', kandidat: 'Ilham Ambia Putra', scores: [
    { kode: 'A100', nilai: 0, check_ada: false },
    { kode: 'A200', nilai: 4, check_ada: true },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 0, check_ada: false },
    { kode: 'C110', nilai: 3, check_ada: false, keterangan: 'BELUM LANCAR, ADA TRAUMA MENGENDARA MOBIL (NABRAK)' },
    { kode: 'C120', nilai: 8, check_ada: false, keterangan: 'MENGETAHUI ALUR DAN ADMINSTRASI LOGISTIK' },
    { kode: 'C130', nilai: 2, check_ada: false },
    { kode: 'C140', nilai: 4.5, check_ada: false, keterangan: 'PERNAH MENGIRIM LANGSUNG KE CUSTOMER' },
    { kode: 'D110', nilai: 2, check_ada: false, keterangan: 'MENCARI SOLUSI BERSAMA DAN MEMBERIKAN SOLUSI' },
    { kode: 'D120', nilai: 10, check_ada: false },
    { kode: 'D130', nilai: 4, check_ada: false, keterangan: 'MEMAKLUMI PERUBAHAN PERATURAN DAN MENGIKUTI' },
    { kode: 'D140', nilai: 4.5, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 4, check_ada: false, keterangan: 'FLEKSIBLE DAN AKAN MENGAMBIL TINDAKAN SESUAI SIKON' },
    { kode: 'E300', nilai: 2, check_ada: false },
    { kode: 'F100', nilai: 2.4, check_ada: false, keterangan: 'TERBUKA UNTUK NEGOSIASI SALARY' },
    { kode: 'F200', nilai: 0.4, check_ada: false, keterangan: 'BELUM ADA TUJUAN KARIR' },
    { kode: 'G100', nilai: 0, check_ada: false }
  ]},
  // === MUCHLIS -> Mohamad Dicky === Excel Total: 52.2, Calculated: 52.2
  { penilai: 'muchlis', kandidat: 'Mohamad Dicky', scores: [
    { kode: 'A100', nilai: 0, check_ada: false },
    { kode: 'A200', nilai: 4, check_ada: true, keterangan: 'PERENCANAAN PROGRAM DESA TERKAIT DANA DESA' },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 1, check_ada: true },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 3, check_ada: false, keterangan: 'TIDAK BISA MOBIL MANUAL, MATIC BELUM LANCAR' },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 1.5, check_ada: false },
    { kode: 'C140', nilai: 1.5, check_ada: false },
    { kode: 'D110', nilai: 2, check_ada: false, keterangan: 'BERDISKUSI DENGAN TIM DAN MENGAMBIL KEPUTUSAN BERSAMA / MENGUSULKAN VOTING' },
    { kode: 'D120', nilai: 8, check_ada: false },
    { kode: 'D130', nilai: 3, check_ada: false, keterangan: 'MENGAMBIL SIKAP MEMPERTANYAKAN KEPENTINGAN MENGUBAH PERATURAN' },
    { kode: 'D140', nilai: 6, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 3, check_ada: false },
    { kode: 'E300', nilai: 2, check_ada: false },
    { kode: 'F100', nilai: 2.4, check_ada: false },
    { kode: 'F200', nilai: 0.8, check_ada: false, keterangan: 'ADA TUJUAN KARIR KE MANAJER' },
    { kode: 'G100', nilai: 0, check_ada: false }
  ]},
  // === MUCHLIS -> M. Doni Waseso === Excel Total: 57.5, Calculated: 57.5
  { penilai: 'muchlis', kandidat: 'M. Doni Waseso', scores: [
    { kode: 'A100', nilai: 6, check_ada: true },
    { kode: 'A200', nilai: 0, check_ada: false },
    { kode: 'B100', nilai: 1, check_ada: true },
    { kode: 'B200', nilai: 0, check_ada: false },
    { kode: 'B300', nilai: 0, check_ada: false },
    { kode: 'B400', nilai: 1, check_ada: true },
    { kode: 'C110', nilai: 9, check_ada: false, keterangan: 'MATIC LANCAR, MANUAL BELUM LANCAR' },
    { kode: 'C120', nilai: 6, check_ada: false },
    { kode: 'C130', nilai: 1.5, check_ada: false },
    { kode: 'C140', nilai: 3, check_ada: false },
    { kode: 'D110', nilai: 1.5, check_ada: false },
    { kode: 'D120', nilai: 4, check_ada: false },
    { kode: 'D130', nilai: 4, check_ada: false },
    { kode: 'D140', nilai: 6, check_ada: false },
    { kode: 'E100', nilai: 6, check_ada: false },
    { kode: 'E200', nilai: 3, check_ada: false },
    { kode: 'E300', nilai: 1.5, check_ada: false },
    { kode: 'F100', nilai: 3.2, check_ada: false },
    { kode: 'F200', nilai: 0.8, check_ada: false },
    { kode: 'G100', nilai: 0, check_ada: false }
  ]}
];
